repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
        exclude_types: [text] # exclude golden files
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args: ["--unsafe"] # Instead of loading the files, simply parse them for syntax
      - id: mixed-line-ending
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0 # Specify the desired version of Gitleaks
    hooks:
      - id: gitleaks
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0
    hooks:
      - id: yamlfmt
